# Generated by Django 5.0.1 on 2024-01-19 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_des', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
