# Generated by Django 5.0.1 on 2024-01-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytask',
            old_name='date',
            new_name='task_date',
        ),
    ]
