# Generated by Django 5.0.1 on 2024-01-20 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_date_mytask_task_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_task_name', models.CharField(max_length=100)),
                ('completed_task_des', models.TextField()),
                ('completed_task_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
